export const techStack = [
  { value: "Node.js", label: "Node.js" },
  { value: "Python", label: "Python" },
  { value: "Java", label: "Java" },
  { value: "Ruby", label: "Ruby" },
  { value: "PHP", label: "PHP" },
  { value: "Go", label: "Go" },
  { value: "C#", label: "C#" },
  { value: "Rust", label: "Rust" },
  { value: "SQL", label: "SQL" },
  { value: "NoSQL", label: "NoSQL" },
  { value: "GraphQL", label: "GraphQL" },
  { value: "RESTful API", label: "RESTful API" },
  { value: "Docker", label: "Docker" },
  { value: "Kubernetes", label: "Kubernetes" },
  { value: "Redis", label: "Redis" },
  { value: "RabbitMQ", label: "RabbitMQ" },
  { value: "Apache Kafka", label: "Apache Kafka" },
  { value: "Elasticsearch", label: "Elasticsearch" },
  { value: "Graph Database", label: "Graph Database" },
  { value: "Firebase", label: "Firebase" },
  { value: "Amazon Web Services (AWS)", label: "Amazon Web Services (AWS)" },
  { value: "Microsoft Azure", label: "Microsoft Azure" },
  { value: "Google Cloud Platform (GCP)", label: "Google Cloud Platform (GCP)" },
  { value: "Terraform", label: "Terraform" },
  { value: "Ansible", label: "Ansible" },
  { value: "Nginx", label: "Nginx" },
  { value: "Apache HTTP Server", label: "Apache HTTP Server" },
  { value: "JWT", label: "JWT" },
  { value: "OAuth", label: "OAuth" },
  { value: "OpenAPI", label: "OpenAPI" },
  { value: "Spring Boot", label: "Spring Boot" },
  { value: "Express.js", label: "Express.js" },
  { value: "Flask", label: "Flask" },
  { value: "Django REST Framework", label: "Django REST Framework" },
  { value: "Koa", label: "Koa" },
  { value: "Haskell", label: "Haskell" },
  { value: "Scala", label: "Scala" },
  { value: "Phoenix", label: "Phoenix" },
  { value: "Sails.js", label: "Sails.js" },
  { value: "Jenkins", label: "Jenkins" },
  { value: "CircleCI", label: "CircleCI" },
  { value: "Travis CI", label: "Travis CI" },
  { value: "PostgreSQL", label: "PostgreSQL" },
  { value: "MySQL", label: "MySQL" },
  { value: "SQLite", label: "SQLite" },
  { value: "Cassandra", label: "Cassandra" },
  { value: "InfluxDB", label: "InfluxDB" },
  { value: "Prometheus", label: "Prometheus" },
  { value: "Grafana", label: "Grafana" },
  { value: "Sentry", label: "Sentry" },
];
